// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "ppt-templ/internal/views/layout"

func About(siteName string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"section page-hero\"><div class=\"container narrow-stack\"><p class=\"section__eyebrow\">How the starter is organized</p><h1 class=\"section__title\">A small structure that is easy to extend.</h1><p class=\"section__copy\">Layouts live separately from shared UI, pages stay thin, and the HTTP layer exposes full-page routes alongside focused HTMX fragment endpoints.</p></div></section><section class=\"section\"><div class=\"container two-column\"><article class=\"card card--tall\"><h2 class=\"card__title\">Server-side structure</h2><ul class=\"card-list\"><li class=\"card-list__item\"><strong class=\"card-list__label\">`cmd/web`</strong> starts the app and server.</li><li class=\"card-list__item\"><strong class=\"card-list__label\">`internal/http`</strong> owns routing and rendering.</li><li class=\"card-list__item\"><strong class=\"card-list__label\">`internal/views/layout`</strong> defines the shared page shell.</li><li class=\"card-list__item\"><strong class=\"card-list__label\">`internal/views/components`</strong> stores reusable UI blocks.</li><li class=\"card-list__item\"><strong class=\"card-list__label\">`internal/views/pages`</strong> contains full-page templates.</li></ul></article><article class=\"card card--tall\"><h2 class=\"card__title\">Frontend rules</h2><ul class=\"card-list\"><li class=\"card-list__item\">Use tokens before hard-coded values.</li><li class=\"card-list__item\">Prefer one BEM block per responsibility.</li><li class=\"card-list__item\">Reach for modifiers before special-case descendant selectors.</li><li class=\"card-list__item\">Keep HTMX swaps focused on one target region.</li><li class=\"card-list__item\">Inline only the smallest shell-critical CSS.</li></ul></article></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(layout.PageProps{
			Title:       "About",
			Description: "Project structure, templ layout composition, and frontend conventions for the starter.",
			SiteName:    siteName,
			BodyClass:   "page--about",
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
