// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "ppt-templ/internal/views/layout"

func Contact(siteName string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"section page-hero\"><div class=\"container narrow-stack\"><p class=\"section__eyebrow\">Conventions in practice</p><h1 class=\"section__title\">Use this page as a starting point for new content routes.</h1><p class=\"section__copy\">Each page should reuse the shared shell, stick to the token palette, and compose blocks instead of redefining layout primitives.</p></div></section><section class=\"section\"><div class=\"container contact-grid\"><article class=\"card\"><h2 class=\"card__title\">Page checklist</h2><ul class=\"card-list\"><li class=\"card-list__item\">Set a page title, description, and body modifier.</li><li class=\"card-list__item\">Compose from shared blocks before adding page-only styles.</li><li class=\"card-list__item\">Keep navigation and footer untouched unless the shell changes for every page.</li></ul></article><article class=\"card\"><h2 class=\"card__title\">Performance checklist</h2><ul class=\"card-list\"><li class=\"card-list__item\">Preserve the critical CSS slice in the layout.</li><li class=\"card-list__item\">Load the primary stylesheet through preload + stylesheet tags.</li><li class=\"card-list__item\">Keep scripts deferred and small.</li></ul></article><article class=\"card\"><h2 class=\"card__title\">Next extension points</h2><ul class=\"card-list\"><li class=\"card-list__item\">Add page-specific blocks when shared components stop fitting.</li><li class=\"card-list__item\">Add additional HTMX endpoints for forms or scoped content refreshes.</li><li class=\"card-list__item\">Introduce asset fingerprinting later if caching becomes important.</li></ul></article></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(layout.PageProps{
			Title:       "Contact",
			Description: "Starter conventions, implementation checklist, and next steps for new pages.",
			SiteName:    siteName,
			BodyClass:   "page--contact",
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
