// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"ppt-templ/internal/content"
	"ppt-templ/internal/views/components"
	"ppt-templ/internal/views/layout"
)

func Home(siteName string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"hero\"><div class=\"container hero__grid\"><div class=\"hero__content\"><p class=\"hero__eyebrow\">Luxury property advisors</p><h1 class=\"hero__title\">Find standout homes, launch-stage projects, and market-ready opportunities.</h1><p class=\"hero__body\">This property starter now supports curated listings, project discovery, a market news section, and a built-in contact modal for faster lead capture.</p><div class=\"hero__actions\"><button class=\"button button--primary\" type=\"button\" data-open-contact>Book a consultation</button> <a class=\"button button--secondary\" href=\"/listings\">Browse listings</a></div></div><div class=\"hero-showcase\"><img class=\"hero-showcase__image\" src=\"/assets/img/hero.avif\" alt=\"Modern luxury property living room\"><div class=\"hero-showcase__panel\"><p class=\"hero-showcase__eyebrow\">This season</p><h2 class=\"hero-showcase__title\">Signature homes in Thu Thiem, Thao Dien, and District 1</h2><p class=\"hero-showcase__body\">Use the updated navigation to move between active listings, projects, and editorial content.</p></div></div></div></section><section class=\"section\"><div class=\"container\"><div class=\"section__heading\"><p class=\"section__eyebrow\">Featured listings</p><h2 class=\"section__title\">A curated set of current homes and rental opportunities.</h2></div><div class=\"property-grid property-grid--compact\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, item := range content.Listings()[:3] {
				templ_7745c5c3_Err = components.ListingCard(item).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div></section><section class=\"section section--accent\"><div class=\"container split-panel\"><div class=\"split-panel__intro\"><p class=\"section__eyebrow\">Project launches</p><h2 class=\"section__title\">Track communities that are pre-launch, launching now, or ready for handover.</h2><p class=\"section__copy\">The projects section includes searchable and stage-based filtering so clients can move quickly from browsing to shortlisting.</p><a class=\"button button--primary\" href=\"/projects\">Explore projects</a></div><div class=\"project-grid project-grid--compact\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, item := range content.Projects()[:2] {
				templ_7745c5c3_Err = components.ProjectCard(item).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div></section><section class=\"section\"><div class=\"container\"><div class=\"section__heading\"><p class=\"section__eyebrow\">Latest news</p><h2 class=\"section__title\">Editorial coverage that supports buyers, sellers, and investors.</h2></div><div class=\"news-grid news-grid--compact\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, article := range content.News()[:3] {
				templ_7745c5c3_Err = components.NewsCard(article).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(layout.PageProps{
			Title:       "Home",
			Description: "Property homepage for premium listings, projects, and market news with a direct inquiry modal.",
			SiteName:    siteName,
			BodyClass:   "page--home",
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
