// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HighlightPanel(audience string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		switch audience {
		case "teams":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"feature-panel feature-panel--teams\" id=\"highlight-panel\"><p class=\"feature-panel__eyebrow\">For product teams</p><h3 class=\"feature-panel__title\">Keep the frontend predictable as more hands touch it.</h3><p class=\"feature-panel__body\">Shared blocks, explicit modifiers, and small HTMX fragments help teams ship pages without inventing a new structure each sprint.</p><ul class=\"feature-panel__list\"><li class=\"feature-panel__item\">BEM naming keeps ownership obvious.</li><li class=\"feature-panel__item\">Shared layout templates prevent duplicated page chrome.</li><li class=\"feature-panel__item\">Fragments stay focused and easy to reason about.</li></ul></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "marketers":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<section class=\"feature-panel feature-panel--marketers\" id=\"highlight-panel\"><p class=\"feature-panel__eyebrow\">For content launches</p><h3 class=\"feature-panel__title\">Launch campaign pages fast without reaching for a JS-heavy stack.</h3><p class=\"feature-panel__body\">This starter keeps delivery simple: templates for consistent page assembly, CSS tokens for brand control, and HTMX for small content interactions.</p><ul class=\"feature-panel__list\"><li class=\"feature-panel__item\">Colors and spacing live in one token layer.</li><li class=\"feature-panel__item\">Each page inherits the same header, nav, and footer shell.</li><li class=\"feature-panel__item\">Critical CSS reduces first-paint friction on content pages.</li></ul></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<section class=\"feature-panel feature-panel--founders\" id=\"highlight-panel\"><p class=\"feature-panel__eyebrow\">For new products</p><h3 class=\"feature-panel__title\">Start with a clean marketing shell and add interactivity only where it pays off.</h3><p class=\"feature-panel__body\">You get full-page server rendering by default, then layer in HTMX where partial swaps improve the experience without increasing client-side complexity.</p><ul class=\"feature-panel__list\"><li class=\"feature-panel__item\">Fast path to branded pages and landing sections.</li><li class=\"feature-panel__item\">Go-native asset serving with no Node dependency.</li><li class=\"feature-panel__item\">Clear conventions documented for the next contributor.</li></ul></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
