// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"footer\"><div class=\"container footer__shell\"><div class=\"footer__brand\"><a class=\"brand\" href=\"/\"><span class=\"brand__mark\">PT</span> <span class=\"brand__text\">PPT Templ Property</span></a><p class=\"footer__copy\">Curated listings, launch-stage projects, market news, and practical inquiry flows for clients exploring premium homes and investment-ready opportunities.</p></div><div class=\"footer__menus\"><div class=\"footer__group\"><p class=\"footer__heading\">Explore</p><a class=\"footer__link\" href=\"/\">Home</a> <a class=\"footer__link\" href=\"/listings\">Listings</a> <a class=\"footer__link\" href=\"/projects\">Projects</a> <a class=\"footer__link\" href=\"/news\">News</a></div><div class=\"footer__group\"><p class=\"footer__heading\">Listing types</p><a class=\"footer__link\" href=\"/listings?category=sale\">Properties for sale</a> <a class=\"footer__link\" href=\"/listings?category=rent\">Properties for rent</a> <a class=\"footer__link\" href=\"/projects?status=launching\">Launching projects</a></div><div class=\"footer__group\"><p class=\"footer__heading\">Company</p><a class=\"footer__link\" href=\"/news\">Insights</a> <a class=\"footer__link\" href=\"/listings\">Portfolio</a> <a class=\"footer__link\" href=\"/\">Contact</a></div></div></div><div class=\"container footer__bottom\"><p class=\"footer__legal\">Privacy Policy</p><p class=\"footer__year\">2024 © PPT Templ Property</p></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
